//! Ghostty configuration schema: types, metadata and documentation.
//! Generated from Ghostty default configuration covering all 200 options.

#[derive(Clone, Copy, Debug, PartialEq)]
pub enum Kind {
    Bool,
    Int { min: i64, max: i64 },
    Float { min: f64, max: f64 },
    Enum(&'static [&'static str]),
    Color { special: &'static [&'static str] },
    Text,
    /// Repeatable key (font-family, env, keybind, palette, ...).
    List,
    /// Comma list where an item may be prefixed with `no-`.
    Flags(&'static [&'static str]),
}

pub struct Opt {
    pub key: &'static str,
    pub label: &'static str,
    pub doc: &'static str,
    pub kind: Kind,
    /// Short usage hint shown under the widget.
    pub hint: &'static str,
    /// Non-empty when the option only applies to one platform.
    pub platform: &'static str,
}

impl Opt {
    /// `true` when the key may appear more than once in the file.
    pub fn repeatable(&self) -> bool {
        matches!(self.kind, Kind::List)
    }
}

pub struct Category {
    pub label: &'static str,
    pub desc: &'static str,
    pub keys: &'static [&'static str],
}

const MACOS: &str = "macOS";
const GTK: &str = "GTK";

/// All 200 Ghostty options, keyed by `key`.
pub static OPTS: &[Opt] = &[
    // ---- 글꼴 -------------------------------------------------------------
    Opt {
        key: "font-family",
        label: "글꼴",
        doc: "Primary font, then fallbacks in preference order. Repeat the key for each fallback. `ghostty +list-fonts` prints the valid names.",
        kind: Kind::List,
        hint: "각 줄에 글꼴 하나",
        platform: "",},
    Opt {
        key: "font-family-bold",
        label: "굵은 글꼴 (Bold)",
        doc: "Ghostty font-family-bold configuration.",
        kind: Kind::List,
        hint: "글꼴명",
        platform: "",
    },
    Opt {
        key: "font-family-italic",
        label: "기울임 글꼴 (Italic)",
        doc: "Ghostty font-family-italic configuration.",
        kind: Kind::List,
        hint: "글꼴명",
        platform: "",
    },
    Opt {
        key: "font-family-bold-italic",
        label: "굵은 기울임 글꼴 (Bold Italic)",
        doc: "Ghostty font-family-bold-italic configuration.",
        kind: Kind::List,
        hint: "글꼴명",
        platform: "",
    },
    Opt {
        key: "font-style",
        label: "글꼴 스타일",
        doc: "Named font style as advertised by the font itself, e.g. \"Iosevka Heavy\". Set to `false` to disable this style entirely.",
        kind: Kind::Text,
        hint: "예: Heavy, false",
        platform: "",},
    Opt {
        key: "font-style-bold",
        label: "굵은 스타일 이름",
        doc: "Ghostty font-style-bold configuration.",
        kind: Kind::Text,
        hint: "예: Bold, default",
        platform: "",
    },
    Opt {
        key: "font-style-italic",
        label: "기울임 스타일 이름",
        doc: "Ghostty font-style-italic configuration.",
        kind: Kind::Text,
        hint: "예: Italic, default",
        platform: "",
    },
    Opt {
        key: "font-style-bold-italic",
        label: "굵은 기울임 스타일 이름",
        doc: "Ghostty font-style-bold-italic configuration.",
        kind: Kind::Text,
        hint: "예: Bold Italic, default",
        platform: "",
    },
    Opt {
        key: "font-size",
        label: "글꼴 크기",
        doc: "Font size in points. Non-integers are allowed (13.5) and round to the nearest pixel on high-DPI displays.",
        kind: Kind::Float { min: 1.0, max: 200.0 },
        hint: "pt",
        platform: "",},
    Opt {
        key: "font-feature",
        label: "OpenType 기능",
        doc: "Font features to apply, e.g. `-calt` to disable programming ligatures. Repeat the key or comma-separate values.",
        kind: Kind::List,
        hint: "예: -calt, -liga, -dlig",
        platform: "",},
    Opt {
        key: "font-thicken",
        label: "글꼴 두껍게",
        doc: "Draw fonts with a thicker stroke.",
        kind: Kind::Bool,
        hint: "",
        platform: MACOS,},
    Opt {
        key: "font-thicken-strength",
        label: "두께 강도",
        doc: "Strength of thickening when font-thicken is enabled. 0 is the lightest, not \"off\".",
        kind: Kind::Int { min: 0, max: 255 },
        hint: "0–255",
        platform: MACOS,},
    Opt {
        key: "font-variation",
        label: "가변 글꼴 축 설정",
        doc: "A repeatable configuration to set one or more font variations values for a variable font. A variable font is a single font, usually with a filename ending in...",
        kind: Kind::List,
        hint: "wght=700",
        platform: "",
    },
    Opt {
        key: "font-variation-bold",
        label: "가변 글꼴 축 (Bold)",
        doc: "Ghostty font-variation-bold configuration.",
        kind: Kind::List,
        hint: "wght=700",
        platform: "",
    },
    Opt {
        key: "font-variation-italic",
        label: "가변 글꼴 축 (Italic)",
        doc: "Ghostty font-variation-italic configuration.",
        kind: Kind::List,
        hint: "wght=700",
        platform: "",
    },
    Opt {
        key: "font-variation-bold-italic",
        label: "가변 글꼴 축 (Bold Italic)",
        doc: "Ghostty font-variation-bold-italic configuration.",
        kind: Kind::List,
        hint: "wght=700",
        platform: "",
    },
    Opt {
        key: "font-codepoint-map",
        label: "글꼴 코드포인트 매핑",
        doc: "Force one or a range of Unicode codepoints to map to a specific named font. This is useful if you want to support special symbols or if you want to use speci...",
        kind: Kind::List,
        hint: "U+XXXX=글꼴명",
        platform: "",
    },
    Opt {
        key: "font-synthetic-style",
        label: "인공 스타일 합성",
        doc: "Control whether Ghostty should synthesize a style if the requested style is not available in the specified font-family.",
        kind: Kind::Flags(&["bold", "italic", "bold-italic"]),
        hint: "",
        platform: "",
    },
    Opt {
        key: "font-shaping-break",
        label: "글꼴 셰이핑 분할 위치",
        doc: "Locations to break font shaping into multiple runs.",
        kind: Kind::Enum(&["cursor", "none"]),
        hint: "",
        platform: "",
    },
    Opt {
        key: "freetype-load-flags",
        label: "FreeType 렌더링 플래그",
        doc: "FreeType load flags to enable. The format of this is a list of flags to enable separated by commas. If you prefix a flag with `no-` then it is disabled. If y...",
        kind: Kind::Flags(&["hinting", "force-autohint", "monochrome", "autohint", "light"]),
        hint: "",
        platform: "",
    },
    Opt {
        key: "adjust-cell-width",
        label: "셀 너비 조정",
        doc: "Amount to change the cell width determined by the font. An integer is an absolute delta, a percentage is relative.",
        kind: Kind::Text,
        hint: "예: 1, -1, 20%, -15%",
        platform: "",},
    Opt {
        key: "adjust-cell-height",
        label: "셀 높이 조정",
        doc: "Amount to change the cell height. Also centers the font in the cell and scales Powerline glyphs with it.",
        kind: Kind::Text,
        hint: "예: 1, -1, 20%, -15%",
        platform: "",},
    Opt {
        key: "adjust-font-baseline",
        label: "글꼴 베이스라인 조정",
        doc: "Distance in pixels or percentage adjustment from the bottom of the cell to the text baseline. Increase to move baseline UP, decrease to move baseline DOWN. S...",
        kind: Kind::Text,
        hint: "px 또는 %",
        platform: "",
    },
    Opt {
        key: "adjust-underline-position",
        label: "밑줄 위치 조정",
        doc: "Distance in pixels or percentage adjustment from the top of the cell to the top of the underline. Increase to move underline DOWN, decrease to move underline...",
        kind: Kind::Text,
        hint: "px 또는 %",
        platform: "",
    },
    Opt {
        key: "adjust-underline-thickness",
        label: "밑줄 두께 조정",
        doc: "Thickness in pixels of the underline. See the notes about adjustments in `adjust-cell-width`.",
        kind: Kind::Text,
        hint: "px 또는 %",
        platform: "",
    },
    Opt {
        key: "adjust-overline-position",
        label: "윗줄 위치 조정",
        doc: "Distance in pixels or percentage adjustment from the top of the cell to the top of the overline. Increase to move overline DOWN, decrease to move overline UP...",
        kind: Kind::Text,
        hint: "px 또는 %",
        platform: "",
    },
    Opt {
        key: "adjust-overline-thickness",
        label: "윗줄 두께 조정",
        doc: "Thickness in pixels or percentage adjustment of the overline. See the notes about adjustments in `adjust-cell-width`.",
        kind: Kind::Text,
        hint: "px 또는 %",
        platform: "",
    },
    Opt {
        key: "adjust-strikethrough-position",
        label: "취소선 위치 조정",
        doc: "Distance in pixels or percentage adjustment from the top of the cell to the top of the strikethrough. Increase to move strikethrough DOWN, decrease to move s...",
        kind: Kind::Text,
        hint: "px 또는 %",
        platform: "",
    },
    Opt {
        key: "adjust-strikethrough-thickness",
        label: "취소선 두께 조정",
        doc: "Thickness in pixels or percentage adjustment of the strikethrough. See the notes about adjustments in `adjust-cell-width`.",
        kind: Kind::Text,
        hint: "px 또는 %",
        platform: "",
    },
    Opt {
        key: "adjust-box-thickness",
        label: "박스 드로잉 두께 조정",
        doc: "Thickness in pixels or percentage adjustment of box drawing characters. See the notes about adjustments in `adjust-cell-width`.",
        kind: Kind::Text,
        hint: "px 또는 %",
        platform: "",
    },
    Opt {
        key: "adjust-icon-height",
        label: "아이콘 높이 조정",
        doc: "Height in pixels or percentage adjustment of maximum height for nerd font icons.",
        kind: Kind::Text,
        hint: "px 또는 %",
        platform: "",
    },
    Opt {
        key: "grapheme-width-method",
        label: "글리프 폭 계산",
        doc: "How to measure grapheme cluster width. `unicode` is correct but can desync with programs using a legacy wcswidth.",
        kind: Kind::Enum(&["unicode", "legacy"]),
        hint: "",
        platform: "",},
    // ---- 테마 · 색상 -------------------------------------------------------------
    Opt {
        key: "theme",
        label: "테마",
        doc: "Built-in theme name, custom theme name, or absolute path. Supports light/dark pairs as `light:Dawn,dark:Rose Pine`.",
        kind: Kind::Text,
        hint: "ghostty +list-themes",
        platform: "",},
    Opt {
        key: "window-theme",
        label: "창 테마",
        doc: "`auto` derives the window theme from the terminal background color; `ghostty` uses the configured colors directly (Linux only).",
        kind: Kind::Enum(&["auto", "system", "light", "dark", "ghostty"]),
        hint: "",
        platform: "",},
    Opt {
        key: "background",
        label: "배경색",
        doc: "Background color for the window.",
        kind: Kind::Color { special: &[] },
        hint: "#RRGGBB 또는 X11 색상명",
        platform: "",},
    Opt {
        key: "foreground",
        label: "글자색",
        doc: "Foreground color for the window.",
        kind: Kind::Color { special: &[] },
        hint: "#RRGGBB 또는 X11 색상명",
        platform: "",},
    Opt {
        key: "bold-color",
        label: "굵은 글자색",
        doc: "Color used for bold text. Set to `bright` to reproduce the old bold-is-bright behavior.",
        kind: Kind::Color { special: &["bright"] },
        hint: "#RRGGBB 또는 bright",
        platform: "",},
    Opt {
        key: "background-opacity",
        label: "배경 불투명도",
        doc: "1 is fully opaque, 0 fully transparent. On macOS changing this requires a full restart.",
        kind: Kind::Float { min: 0.0, max: 1.0 },
        hint: "0.0 – 1.0",
        platform: "",},
    Opt {
        key: "background-opacity-cells",
        label: "셀 배경 불투명도 적용",
        doc: "Applies background opacity to cells with an explicit background color set.",
        kind: Kind::Bool,
        hint: "",
        platform: "",
    },
    Opt {
        key: "background-blur",
        label: "배경 블러",
        doc: "Blur behind a translucent background. Accepts true, false, an intensity (default 20), or on macOS 26+ `macos-glass-regular` / `macos-glass-clear`.",
        kind: Kind::Text,
        hint: "true / false / 정수 / macos-glass-*",
        platform: "",},
    Opt {
        key: "background-image",
        label: "배경 이미지",
        doc: "Background image for the terminal.",
        kind: Kind::Text,
        hint: "이미지 파일 경로",
        platform: "",
    },
    Opt {
        key: "background-image-opacity",
        label: "배경 이미지 불투명도",
        doc: "Background image opacity.",
        kind: Kind::Float { min: 0.0, max: 1.0 },
        hint: "0.0 – 1.0",
        platform: "",
    },
    Opt {
        key: "background-image-position",
        label: "배경 이미지 위치",
        doc: "Background image position.",
        kind: Kind::Enum(&["center", "top", "bottom", "left", "right", "top-left", "top-right", "bottom-left", "bottom-right"]),
        hint: "",
        platform: "",
    },
    Opt {
        key: "background-image-repeat",
        label: "배경 이미지 반복",
        doc: "Whether to repeat the background image or not.",
        kind: Kind::Bool,
        hint: "",
        platform: "",
    },
    Opt {
        key: "background-image-fit",
        label: "배경 이미지 맞춤",
        doc: "Background image fit.",
        kind: Kind::Enum(&["contain", "cover", "fill", "none"]),
        hint: "",
        platform: "",
    },
    Opt {
        key: "minimum-contrast",
        label: "최소 대비",
        doc: "Minimum WCAG contrast ratio between foreground and background. 1 allows no contrast; 3+ avoids hard-to-read text.",
        kind: Kind::Float { min: 1.0, max: 21.0 },
        hint: "1 – 21",
        platform: "",},
    Opt {
        key: "faint-opacity",
        label: "흐린 글자 불투명도",
        doc: "The opacity level (opposite of transparency) of the faint text. A value of 1 is fully opaque and a value of 0 is fully transparent. A value less than 0 or gr...",
        kind: Kind::Float { min: 0.0, max: 1.0 },
        hint: "0.0 – 1.0",
        platform: "",
    },
    Opt {
        key: "alpha-blending",
        label: "알파 블렌딩 색공간",
        doc: "What color space to use when performing alpha blending.",
        kind: Kind::Enum(&["native", "linear"]),
        hint: "",
        platform: "",
    },
    Opt {
        key: "palette",
        label: "색상 팔레트",
        doc: "The 256-color table, as `N=#COLOR`. You usually only need indices 0–15; 16–255 can be generated with palette-generate.",
        kind: Kind::List,
        hint: "각 줄에 0=#RRGGBB",
        platform: "",},
    Opt {
        key: "palette-generate",
        label: "256색 팔레트 자동 생성",
        doc: "Whether to automatically generate the extended 256 color palette (indices 16–255) from the base 16 ANSI colors.",
        kind: Kind::Bool,
        hint: "",
        platform: "",
    },
    Opt {
        key: "palette-harmonious",
        label: "조화로운 팔레트 색상 반전",
        doc: "Invert the palette colors generated when `palette-generate` is enabled, so that the colors go in reverse order. This allows palette-based applications to wor...",
        kind: Kind::Bool,
        hint: "",
        platform: "",
    },
    Opt {
        key: "search-background",
        label: "검색 일치 배경색",
        doc: "Ghostty search-background configuration.",
        kind: Kind::Color { special: &[] },
        hint: "#RRGGBB",
        platform: "",
    },
    Opt {
        key: "search-foreground",
        label: "검색 일치 글자색",
        doc: "The foreground and background color for search matches. This only applies to non-focused search matches, also known as candidate matches.",
        kind: Kind::Color { special: &[] },
        hint: "#RRGGBB",
        platform: "",
    },
    Opt {
        key: "search-selected-background",
        label: "선택된 검색 일치 배경색",
        doc: "Ghostty search-selected-background configuration.",
        kind: Kind::Color { special: &[] },
        hint: "#RRGGBB",
        platform: "",
    },
    Opt {
        key: "search-selected-foreground",
        label: "선택된 검색 일치 글자색",
        doc: "The foreground and background color for the currently selected search match. This is the focused match that will be jumped to when using next/previous search...",
        kind: Kind::Color { special: &[] },
        hint: "#RRGGBB",
        platform: "",
    },
    Opt {
        key: "split-divider-color",
        label: "화면 분할선 색상",
        doc: "The color of the split divider. If this is not set, a default will be chosen. Specified as either hex (`#RRGGBB` or `RRGGBB`) or a named X11 color.",
        kind: Kind::Color { special: &[] },
        hint: "#RRGGBB",
        platform: "",
    },
    Opt {
        key: "unfocused-split-fill",
        label: "비활성 분할 채우기 색상",
        doc: "The color to dim the unfocused split. Unfocused splits are dimmed by rendering a semi-transparent rectangle over the split. This sets the color of that recta...",
        kind: Kind::Color { special: &[] },
        hint: "#RRGGBB",
        platform: "",
    },
    Opt {
        key: "unfocused-split-opacity",
        label: "비활성 분할 불투명도",
        doc: "The opacity level (opposite of transparency) of an unfocused split. Unfocused splits by default are slightly faded out to make it easier to see which split i...",
        kind: Kind::Float { min: 0.0, max: 1.0 },
        hint: "0.0 – 1.0",
        platform: "",
    },
    Opt {
        key: "window-padding-color",
        label: "창 여백 영역 색상",
        doc: "The color of the padding area of the window. Valid values are:",
        kind: Kind::Enum(&["background", "extend"]),
        hint: "",
        platform: "",
    },
    Opt {
        key: "window-titlebar-background",
        label: "창 타이틀바 배경색",
        doc: "Background color for the window titlebar. This only takes effect if window-theme is set to ghostty. Currently only supported in the GTK app runtime.",
        kind: Kind::Color { special: &[] },
        hint: "#RRGGBB",
        platform: "",
    },
    Opt {
        key: "window-titlebar-foreground",
        label: "창 타이틀바 글자색",
        doc: "Foreground color for the window titlebar. This only takes effect if window-theme is set to ghostty. Currently only supported in the GTK app runtime.",
        kind: Kind::Color { special: &[] },
        hint: "#RRGGBB",
        platform: "",
    },
    // ---- 커서 -------------------------------------------------------------
    Opt {
        key: "cursor-style",
        label: "커서 모양",
        doc: "Default cursor style. A running program can still override it with DECSCUSR, and shell integration forces a bar at prompts unless disabled.",
        kind: Kind::Enum(&["block", "bar", "underline", "block_hollow"]),
        hint: "",
        platform: "",},
    Opt {
        key: "cursor-style-blink",
        label: "커서 깜빡임",
        doc: "Default blinking state. Leaving this unset lets Ghostty honour DEC mode 12 as well as DECSCUSR.",
        kind: Kind::Enum(&["true", "false"]),
        hint: "기본값 = DEC mode 12 준수",
        platform: "",},
    Opt {
        key: "cursor-color",
        label: "커서 색",
        doc: "Color of the cursor, or a special value to track the cell underneath it.",
        kind: Kind::Color { special: &["cell-foreground", "cell-background"] },
        hint: "#RRGGBB 또는 cell-foreground",
        platform: "",},
    Opt {
        key: "cursor-text",
        label: "커서 위 글자색",
        doc: "Color of the text under the cursor.",
        kind: Kind::Color { special: &["cell-foreground", "cell-background"] },
        hint: "#RRGGBB",
        platform: "",},
    Opt {
        key: "cursor-opacity",
        label: "커서 불투명도",
        doc: "1 is fully opaque, 0 fully transparent. Values far below 1 make the cursor hard to find.",
        kind: Kind::Float { min: 0.0, max: 1.0 },
        hint: "0.0 – 1.0",
        platform: "",},
    Opt {
        key: "cursor-click-to-move",
        label: "클릭으로 커서 이동",
        doc: "Move the cursor at a shell prompt by clicking in the prompt text. Requires prompt marking (OSC 133) via shell integration.",
        kind: Kind::Bool,
        hint: "",
        platform: "",},
    Opt {
        key: "adjust-cursor-height",
        label: "커서 높이 조정",
        doc: "Height in pixels or percentage adjustment of the cursor. Currently applies to all cursor types: bar, rect, and outlined rect. See the notes about adjustments...",
        kind: Kind::Text,
        hint: "px 또는 %",
        platform: "",
    },
    Opt {
        key: "adjust-cursor-thickness",
        label: "커서 두께 조정",
        doc: "Thickness in pixels or percentage adjustment of the bar cursor and outlined rect cursor. See the notes about adjustments in `adjust-cell-width`.",
        kind: Kind::Text,
        hint: "px 또는 %",
        platform: "",
    },
    // ---- 선택 · 클립보드 -------------------------------------------------------------
    Opt {
        key: "selection-background",
        label: "선택 영역 배경",
        doc: "Selection background. Unset, selection is drawn as the inverted window colors.",
        kind: Kind::Color { special: &["cell-foreground", "cell-background"] },
        hint: "#RRGGBB",
        platform: "",},
    Opt {
        key: "selection-foreground",
        label: "선택 영역 글자색",
        doc: "Selection foreground.",
        kind: Kind::Color { special: &["cell-foreground", "cell-background"] },
        hint: "#RRGGBB",
        platform: "",},
    Opt {
        key: "selection-clear-on-typing",
        label: "입력 시 선택 해제",
        doc: "Clear the selection when a non-modifier key sends data to the application. Clearing still works via a click or Escape when off.",
        kind: Kind::Bool,
        hint: "",
        platform: "",},
    Opt {
        key: "selection-clear-on-copy",
        label: "복사 후 선택 영역 해제",
        doc: "Whether to clear selected text after copying. This defaults to `false`.",
        kind: Kind::Bool,
        hint: "",
        platform: "",
    },
    Opt {
        key: "copy-on-select",
        label: "선택 시 복사",
        doc: "`true` prefers the selection clipboard; `clipboard` writes both the selection and system clipboard. Middle-click paste always works.",
        kind: Kind::Enum(&["true", "false", "clipboard"]),
        hint: "",
        platform: "",},
    Opt {
        key: "selection-word-chars",
        label: "단어 경계 문자",
        doc: "Characters that bound a double-click word selection, like WORDCHARS in zsh. Each character is a boundary; sequences are not supported.",
        kind: Kind::Text,
        hint: "기본: \\t'\"│`|:;,()[]{}<>$",
        platform: "",},
    Opt {
        key: "clipboard-paste-protection",
        label: "붙여넣기 보호",
        doc: "Confirm before pasting control characters that could execute in a shell.",
        kind: Kind::Bool,
        hint: "",
        platform: "",},
    Opt {
        key: "clipboard-paste-bracketed-safe",
        label: "Bracketed 붙여넣기 안전 모드",
        doc: "If true, bracketed pastes will be considered safe. By default, bracketed pastes are considered safe. \"Bracketed\" pastes are pastes while the running progra...",
        kind: Kind::Bool,
        hint: "",
        platform: "",
    },
    Opt {
        key: "clipboard-trim-trailing-spaces",
        label: "복사 시 공백 정리",
        doc: "Trim trailing spaces from each line when copying.",
        kind: Kind::Bool,
        hint: "",
        platform: "",},
    Opt {
        key: "clipboard-read",
        label: "클립보드 읽기 권한",
        doc: "Whether to allow programs running in the terminal to read/write to the system clipboard (OSC 52, for googling). The default is to allow clipboard reading aft...",
        kind: Kind::Enum(&["ask", "allow", "deny"]),
        hint: "",
        platform: "",
    },
    Opt {
        key: "clipboard-write",
        label: "클립보드 쓰기 권한",
        doc: "Ghostty clipboard-write configuration.",
        kind: Kind::Enum(&["ask", "allow", "deny"]),
        hint: "",
        platform: "",
    },
    Opt {
        key: "clipboard-codepoint-map",
        label: "클립보드 코드포인트 매핑",
        doc: "Map specific Unicode codepoints to replacement values when copying text to clipboard.",
        kind: Kind::List,
        hint: "U+XXXX=문자",
        platform: "",
    },
    // ---- 창 · 탭 -------------------------------------------------------------
    Opt {
        key: "window-width",
        label: "창 너비",
        doc: "Initial window width in terminal grid cells. Ignored unless window-height is also set.",
        kind: Kind::Int { min: 1, max: 10000 },
        hint: "글리프 셀 수",
        platform: "",},
    Opt {
        key: "window-height",
        label: "창 높이",
        doc: "Initial window height in terminal grid cells. Ignored unless window-width is also set.",
        kind: Kind::Int { min: 1, max: 10000 },
        hint: "글리프 셀 수",
        platform: "",},
    Opt {
        key: "window-padding-x",
        label: "가로 여백",
        doc: "Horizontal padding in points. Give two comma-separated values to set left and right independently.",
        kind: Kind::Text,
        hint: "예: 4 또는 2,4",
        platform: "",},
    Opt {
        key: "window-padding-y",
        label: "세로 여백",
        doc: "Vertical padding in points. Give two comma-separated values to set top and bottom independently.",
        kind: Kind::Text,
        hint: "예: 4 또는 2,4",
        platform: "",},
    Opt {
        key: "window-padding-balance",
        label: "창 여백 균등 분배",
        doc: "The viewport dimensions are usually not perfectly divisible by the cell size. In this case, some extra padding on the end of a column and the bottom of the f...",
        kind: Kind::Bool,
        hint: "",
        platform: "",
    },
    Opt {
        key: "window-position-x",
        label: "창 시작 X 좌표",
        doc: "The starting window position. This position is in pixels and is relative to the top-left corner of the primary monitor. Both values must be set to take effec...",
        kind: Kind::Text,
        hint: "px 또는 center",
        platform: "",
    },
    Opt {
        key: "window-position-y",
        label: "창 시작 Y 좌표",
        doc: "Ghostty window-position-y configuration.",
        kind: Kind::Text,
        hint: "px 또는 center",
        platform: "",
    },
    Opt {
        key: "window-decoration",
        label: "창 장식",
        doc: "Preference for titlebar and borders. The OS may override it. `none` also disables macOS tabs.",
        kind: Kind::Enum(&["auto", "none", "client", "server"]),
        hint: "",
        platform: "",},
    Opt {
        key: "window-save-state",
        label: "창 상태 저장",
        doc: "Save and restore position, size, tabs and splits. macOS only.",
        kind: Kind::Enum(&["default", "never", "always"]),
        hint: "",
        platform: MACOS,},
    Opt {
        key: "window-step-resize",
        label: "셀 단위 크기 조절",
        doc: "Resize the window in whole cell increments instead of pixel increments.",
        kind: Kind::Bool,
        hint: "",
        platform: MACOS,},
    Opt {
        key: "window-new-tab-position",
        label: "새 탭 위치",
        doc: "Where a newly created tab is inserted.",
        kind: Kind::Enum(&["current", "end"]),
        hint: "",
        platform: "",},
    Opt {
        key: "window-show-tab-bar",
        label: "탭 표시줄",
        doc: "`auto` shows the bar only with two or more tabs. Linux only.",
        kind: Kind::Enum(&["auto", "always", "never"]),
        hint: "",
        platform: GTK,},
    Opt {
        key: "window-vsync",
        label: "수직 동기화 (VSync)",
        doc: "Synchronize rendering with the screen refresh rate. If true, this will minimize tearing and align redraws with the screen but may cause input latency. If fal...",
        kind: Kind::Bool,
        hint: "",
        platform: "",
    },
    Opt {
        key: "window-colorspace",
        label: "창 색공간",
        doc: "The color space to use when interpreting terminal colors. \"Terminal colors\" refers to colors specified in your configuration and colors produced by direct-...",
        kind: Kind::Enum(&["srgb", "display-p3"]),
        hint: "",
        platform: "",
    },
    Opt {
        key: "window-inherit-working-directory",
        label: "새 창 작업 디렉터리 상속",
        doc: "If true, new windows will inherit the working directory of the previously focused window. If no window was previously focused, the default working directory ...",
        kind: Kind::Bool,
        hint: "",
        platform: "",
    },
    Opt {
        key: "window-inherit-font-size",
        label: "새 창 글꼴 크기 상속",
        doc: "If true, new windows and tabs will inherit the font size of the previously focused window. If no window was previously focused, the default font size will be...",
        kind: Kind::Bool,
        hint: "",
        platform: "",
    },
    Opt {
        key: "window-subtitle",
        label: "창 부제목",
        doc: "The text that will be displayed in the subtitle of the window. Valid values:",
        kind: Kind::Text,
        hint: "",
        platform: MACOS,
    },
    Opt {
        key: "window-title-font-family",
        label: "창 제목 글꼴",
        doc: "The font that will be used for the application's window and tab titles.",
        kind: Kind::Text,
        hint: "글꼴명",
        platform: MACOS,
    },
    Opt {
        key: "initial-window",
        label: "시작 시 첫 창 생성",
        doc: "This controls whether an initial window is created when Ghostty is run. Note that if `quit-after-last-window-closed` is `true` and `quit-after-last-window-cl...",
        kind: Kind::Bool,
        hint: "",
        platform: "",
    },
    Opt {
        key: "fullscreen",
        label: "전체화면으로 시작",
        doc: "Start new windows in fullscreen. This setting applies to new windows and does not apply to tabs, splits, etc. However, this setting will apply to all new win...",
        kind: Kind::Bool,
        hint: "",
        platform: "",
    },
    Opt {
        key: "maximize",
        label: "최대화 상태로 시작",
        doc: "Whether to start the window in a maximized state. This setting applies to new windows and does not apply to tabs, splits, etc. However, this setting will app...",
        kind: Kind::Bool,
        hint: "",
        platform: "",
    },
    Opt {
        key: "macos-titlebar-style",
        label: "macOS 타이틀바",
        doc: "`transparent` lets the terminal background show through; `tabs` folds the tab bar into the titlebar; `hidden` keeps the frame and rounded corners.",
        kind: Kind::Enum(&["native", "transparent", "tabs", "hidden"]),
        hint: "",
        platform: MACOS,},
    Opt {
        key: "macos-titlebar-proxy-icon",
        label: "타이틀바 프록시 아이콘",
        doc: "Whether the proxy icon in the macOS titlebar is visible. The proxy icon is the icon that represents the folder of the current working directory. You can see ...",
        kind: Kind::Enum(&["visible", "hidden"]),
        hint: "",
        platform: MACOS,
    },
    Opt {
        key: "macos-window-buttons",
        label: "macOS 신호등 버튼",
        doc: "Show or hide the close/minimize/zoom buttons. No effect when window-decoration is none or the titlebar is hidden.",
        kind: Kind::Enum(&["visible", "hidden"]),
        hint: "",
        platform: MACOS,},
    Opt {
        key: "macos-window-shadow",
        label: "macOS 창 그림자",
        doc: "Whether to enable the macOS window shadow. The default value is true. With some window managers and window transparency settings, you may find false more vis...",
        kind: Kind::Bool,
        hint: "",
        platform: MACOS,
    },
    Opt {
        key: "macos-non-native-fullscreen",
        label: "전체화면 방식",
        doc: "Non-native fullscreen is faster but breaks macOS tabs. `padded-notch` keeps the notch area clear.",
        kind: Kind::Enum(&["false", "true", "visible-menu", "padded-notch"]),
        hint: "",
        platform: MACOS,},
    Opt {
        key: "macos-option-as-alt",
        label: "Option을 Alt로",
        doc: "Treat the Option key as Alt so terminal sequences work, at the cost of Unicode input sequences produced with Option.",
        kind: Kind::Enum(&["true", "false", "left", "right"]),
        hint: "기본값은 키보드 레이아웃에 따라 다름",
        platform: MACOS,},
    Opt {
        key: "macos-hidden",
        label: "Dock/앱 전환기 숨기기",
        doc: "If true, the macOS icon in the dock and app switcher will be hidden. This is mainly intended for those primarily using the quick-terminal mode.",
        kind: Kind::Enum(&["never", "always"]),
        hint: "",
        platform: MACOS,
    },
    Opt {
        key: "macos-icon",
        label: "macOS 앱 아이콘",
        doc: "Customize the macOS app icon.",
        kind: Kind::Enum(&["official", "blueprint", "classic", "custom"]),
        hint: "",
        platform: MACOS,
    },
    Opt {
        key: "macos-icon-frame",
        label: "macOS 아이콘 프레임",
        doc: "The material to use for the frame of the macOS app icon.",
        kind: Kind::Enum(&["aluminum", "beige", "chrome", "copper", "glass", "gold"]),
        hint: "",
        platform: MACOS,
    },
    Opt {
        key: "macos-icon-ghost-color",
        label: "macOS 아이콘 유령 색상",
        doc: "The color of the ghost in the macOS app icon.",
        kind: Kind::Color { special: &[] },
        hint: "#RRGGBB",
        platform: MACOS,
    },
    Opt {
        key: "macos-icon-screen-color",
        label: "macOS 아이콘 화면 색상",
        doc: "The color of the screen in the macOS app icon.",
        kind: Kind::Color { special: &[] },
        hint: "#RRGGBB",
        platform: MACOS,
    },
    Opt {
        key: "macos-custom-icon",
        label: "macOS 커스텀 아이콘",
        doc: "The absolute path to the custom icon file. Supported formats include PNG, JPEG, and ICNS.",
        kind: Kind::Text,
        hint: "icns/png 파일 경로",
        platform: MACOS,
    },
    Opt {
        key: "macos-dock-drop-behavior",
        label: "Dock 드롭 시 동작",
        doc: "Controls the windowing behavior when dropping a file or folder onto the Ghostty icon in the macOS dock.",
        kind: Kind::Enum(&["new-tab", "new-window"]),
        hint: "",
        platform: MACOS,
    },
    Opt {
        key: "macos-applescript",
        label: "AppleScript 연동",
        doc: "If true, Ghostty exposes and handles the built-in AppleScript dictionary on macOS.",
        kind: Kind::Bool,
        hint: "",
        platform: MACOS,
    },
    Opt {
        key: "gtk-titlebar",
        label: "GTK 타이틀바 표시",
        doc: "When enabled, the full GTK titlebar is displayed instead of your window manager's simple titlebar. The behavior of this option will vary with your window man...",
        kind: Kind::Bool,
        hint: "",
        platform: GTK,
    },
    Opt {
        key: "gtk-titlebar-style",
        label: "GTK 타이틀바 스타일",
        doc: "The style of the GTK titlebar. Available values are `native` and `tabs`.",
        kind: Kind::Enum(&["native", "flat"]),
        hint: "",
        platform: GTK,
    },
    Opt {
        key: "gtk-titlebar-hide-when-maximized",
        label: "최대화 시 GTK 타이틀바 숨기기",
        doc: "If this is `true`, the titlebar will be hidden when the window is maximized, and shown when the titlebar is unmaximized. GTK only.",
        kind: Kind::Bool,
        hint: "",
        platform: GTK,
    },
    Opt {
        key: "gtk-toolbar-style",
        label: "GTK 툴바 스타일",
        doc: "Determines the appearance of the top and bottom bars tab bar.",
        kind: Kind::Enum(&["raised", "flat"]),
        hint: "",
        platform: GTK,
    },
    Opt {
        key: "gtk-tabs-location",
        label: "GTK 탭 위치",
        doc: "Determines the side of the screen that the GTK tab bar will stick to. Top, bottom, and hidden are supported. The default is top.",
        kind: Kind::Enum(&["top", "bottom", "left", "right"]),
        hint: "",
        platform: GTK,
    },
    Opt {
        key: "gtk-wide-tabs",
        label: "GTK 넓은 탭",
        doc: "If `true` (default), then the Ghostty GTK tabs will be \"wide.\" Wide tabs are the new typical Gnome style where tabs fill their available space. If you set ...",
        kind: Kind::Bool,
        hint: "",
        platform: GTK,
    },
    Opt {
        key: "gtk-single-instance",
        label: "GTK 단일 인스턴스",
        doc: "If `true`, the Ghostty GTK application will run in single-instance mode: each new `ghostty` process launched will result in a new window if there is already ...",
        kind: Kind::Enum(&["detect", "true", "false"]),
        hint: "",
        platform: GTK,
    },
    Opt {
        key: "gtk-custom-css",
        label: "GTK 커스텀 CSS",
        doc: "Custom CSS files to be loaded.",
        kind: Kind::Text,
        hint: "CSS 파일 경로",
        platform: GTK,
    },
    Opt {
        key: "gtk-opengl-debug",
        label: "GTK OpenGL 디버그 로그",
        doc: "Enable or disable GTK's OpenGL debugging logs. The default is `true` for debug builds, `false` for all others.",
        kind: Kind::Bool,
        hint: "",
        platform: GTK,
    },
    Opt {
        key: "gtk-quick-terminal-layer",
        label: "GTK 퀵 터미널 레이어",
        doc: "The layer of the quick terminal window. The higher the layer, the more windows the quick terminal may conceal.",
        kind: Kind::Enum(&["top", "bottom", "overlay", "background"]),
        hint: "",
        platform: GTK,
    },
    Opt {
        key: "gtk-quick-terminal-namespace",
        label: "GTK 퀵 터미널 네임스페이스",
        doc: "The namespace for the quick terminal window.",
        kind: Kind::Text,
        hint: "",
        platform: GTK,
    },
    Opt {
        key: "quick-terminal-position",
        label: "퀵 터미널 표시 위치",
        doc: "The position of the \"quick\" terminal window. To learn more about the quick terminal, see the documentation for the `toggle_quick_terminal` binding action.",
        kind: Kind::Enum(&["top", "bottom", "left", "right", "center"]),
        hint: "",
        platform: "",
    },
    Opt {
        key: "quick-terminal-screen",
        label: "퀵 터미널 모니터 화면",
        doc: "The screen where the quick terminal should show up.",
        kind: Kind::Enum(&["main", "mouse"]),
        hint: "",
        platform: "",
    },
    Opt {
        key: "quick-terminal-animation-duration",
        label: "퀵 터미널 애니메이션 시간",
        doc: "Duration (in seconds) of the quick terminal enter and exit animation. Set it to 0 to disable animation completely. This can be changed at runtime.",
        kind: Kind::Float { min: 0.0, max: 2.0 },
        hint: "초 (0.0 – 2.0)",
        platform: "",
    },
    Opt {
        key: "quick-terminal-autohide",
        label: "퀵 터미널 자동 숨기기",
        doc: "Automatically hide the quick terminal when focus shifts to another window. Set it to false for the quick terminal to remain open even when it loses focus.",
        kind: Kind::Bool,
        hint: "",
        platform: "",
    },
    Opt {
        key: "quick-terminal-keyboard-interactivity",
        label: "퀵 터미널 키보드 상호작용",
        doc: "Determines under which circumstances that the quick terminal should receive keyboard input. See the corresponding [Wayland documentation](https://wayland.app...",
        kind: Kind::Enum(&["on-demand", "automatic", "none"]),
        hint: "",
        platform: "",
    },
    Opt {
        key: "quick-terminal-space-behavior",
        label: "퀵 터미널 가상 데스크톱 동작",
        doc: "This configuration option determines the behavior of the quick terminal when switching between macOS spaces. macOS spaces are virtual desktops that can be ma...",
        kind: Kind::Enum(&["move", "remain"]),
        hint: "",
        platform: MACOS,
    },
    Opt {
        key: "tab-inherit-working-directory",
        label: "새 탭 작업 디렉터리 상속",
        doc: "If true, new tabs will inherit the working directory of the previously focused tab. If no tab was previously focused, the default working directory will be u...",
        kind: Kind::Bool,
        hint: "",
        platform: "",
    },
    Opt {
        key: "split-inherit-working-directory",
        label: "분할 창 작업 디렉터리 상속",
        doc: "If true, new split panes will inherit the working directory of the previously focused split. If no split was previously focused, the default working director...",
        kind: Kind::Bool,
        hint: "",
        platform: "",
    },
    Opt {
        key: "split-preserve-zoom",
        label: "분할 줌 상태 유지",
        doc: "Control when Ghostty preserves a zoomed split. Under normal circumstances, any operation that changes focus or layout of the split tree in a window will unzo...",
        kind: Kind::Enum(&["no-navigation", "always", "never"]),
        hint: "",
        platform: "",
    },
    // ---- 셸 · 실행 -------------------------------------------------------------
    Opt {
        key: "command",
        label: "실행 명령",
        doc: "Command to run, usually a shell. Searched on PATH if not absolute. Prefix `direct:` to skip shell expansion or `shell:` to force it.",
        kind: Kind::Text,
        hint: "예: /bin/zsh, direct:nvim foo",
        platform: "",},
    Opt {
        key: "initial-command",
        label: "최초 실행 명령",
        doc: "This is the same as \"command\", but only applies to the first terminal surface created when Ghostty starts. Subsequent terminal surfaces will use the `comma...",
        kind: Kind::Text,
        hint: "최초 창에서만 실행할 명령",
        platform: "",
    },
    Opt {
        key: "working-directory",
        label: "작업 디렉터리",
        doc: "Working directory for new terminals. A path starting with `~` is expanded.",
        kind: Kind::Text,
        hint: "예: ~",
        platform: "",},
    Opt {
        key: "input",
        label: "시작 입력 데이터",
        doc: "Data to send as input to the command on startup.",
        kind: Kind::Text,
        hint: "시작 시 입력할 텍스트",
        platform: "",
    },
    Opt {
        key: "shell-integration",
        label: "셸 통합",
        doc: "Auto-inject shell integration, or name the shell to inject into. Integration gives prompt marking, working directory reporting and inherited splits.",
        kind: Kind::Enum(&["detect", "none", "bash", "elvish", "fish", "nushell", "zsh"]),
        hint: "",
        platform: "",},
    Opt {
        key: "shell-integration-features",
        label: "셸 통합 기능",
        doc: "Features to enable. Prefix with `no-` to disable, or use true/false for everything.",
        kind: Kind::Flags(&["cursor", "sudo", "title", "ssh-env", "ssh-terminfo", "path"]),
        hint: "",
        platform: "",},
    Opt {
        key: "env",
        label: "환경 변수",
        doc: "Extra environment variables passed to commands launched in a terminal surface. An empty value removes that key.",
        kind: Kind::List,
        hint: "각 줄에 KEY=VALUE",
        platform: "",},
    Opt {
        key: "term",
        label: "TERM 환경 변수",
        doc: "This will be used to set the `TERM` environment variable. HACK: We set this with an `xterm` prefix because vim uses that to enable key protocols (specificall...",
        kind: Kind::Text,
        hint: "예: xterm-ghostty",
        platform: "",
    },
    Opt {
        key: "enquiry-response",
        label: "ENQ 질의 응답 문자열",
        doc: "String to send when we receive `ENQ` (`0x05`) from the command that we are running. Defaults to an empty string if not set.",
        kind: Kind::Text,
        hint: "",
        platform: "",
    },
    Opt {
        key: "vt-kam-allowed",
        label: "키보드 동작 모드 허용 (KAM)",
        doc: "If true, allows the \"KAM\" mode (ANSI mode 2) to be used within the terminal. KAM disables keyboard input at the request of the application. This is not a c...",
        kind: Kind::Bool,
        hint: "",
        platform: "",
    },
    Opt {
        key: "class",
        label: "애플리케이션 클래스",
        doc: "The setting that will change the application class value.",
        kind: Kind::Text,
        hint: "창 클래스명",
        platform: GTK,
    },
    Opt {
        key: "x11-instance-name",
        label: "X11 인스턴스 이름",
        doc: "This controls the instance name field of the `WM_CLASS` X11 property when running under X11. It has no effect otherwise.",
        kind: Kind::Text,
        hint: "WM_CLASS 이름",
        platform: GTK,
    },
    Opt {
        key: "linux-cgroup",
        label: "Linux cgroup 격리",
        doc: "Put every surface (tab, split, window) into a transient `systemd` scope.",
        kind: Kind::Enum(&["never", "always", "single-instance"]),
        hint: "",
        platform: GTK,
    },
    Opt {
        key: "linux-cgroup-hard-fail",
        label: "Linux cgroup 실패 시 중단",
        doc: "If this is false, then creating a transient `systemd` scope (for `linux-cgroup`) will be allowed to fail and the failure is ignored. This is useful if you vi...",
        kind: Kind::Bool,
        hint: "",
        platform: GTK,
    },
    Opt {
        key: "linux-cgroup-memory-limit",
        label: "Linux cgroup 메모리 한도",
        doc: "Memory limit for any individual terminal process (tab, split, window, etc.) in bytes. If this is unset then no memory limit will be set.",
        kind: Kind::Text,
        hint: "예: 2G",
        platform: GTK,
    },
    Opt {
        key: "linux-cgroup-processes-limit",
        label: "Linux cgroup 프로세스 한도",
        doc: "Number of processes limit for any individual terminal process (tab, split, window, etc.). If this is unset then no limit will be set.",
        kind: Kind::Int { min: 0, max: 100000 },
        hint: "프로세스 수",
        platform: GTK,
    },
    Opt {
        key: "abnormal-command-exit-runtime",
        label: "비정상 종료 기준 시간",
        doc: "The number of milliseconds of runtime below which we consider a process exit to be abnormal. This is used to show an error message when the process exits too...",
        kind: Kind::Int { min: 0, max: 100000 },
        hint: "ms",
        platform: "",
    },
    Opt {
        key: "notify-on-command-finish",
        label: "명령 종료 알림",
        doc: "When to notify that a command finished. Requires shell integration or OSC 133 from the shell.",
        kind: Kind::Enum(&["never", "unfocused", "always"]),
        hint: "",
        platform: "",},
    Opt {
        key: "notify-on-command-finish-action",
        label: "명령 종료 알림 방식",
        doc: "If command finished notifications are enabled, this controls how the user is notified.",
        kind: Kind::Flags(&["bell", "notify"]),
        hint: "",
        platform: "",
    },
    Opt {
        key: "notify-on-command-finish-after",
        label: "명령 종료 알림 지연 시간",
        doc: "If command finished notifications are enabled, this controls how long a command must have been running before a notification will be sent. The default is fiv...",
        kind: Kind::Text,
        hint: "예: 5s, 1m",
        platform: "",
    },
    Opt {
        key: "wait-after-command",
        label: "종료 후 대기",
        doc: "Keep the terminal open after the command exits, until a key is pressed. Useful for scripts and debugging.",
        kind: Kind::Bool,
        hint: "",
        platform: "",},
    Opt {
        key: "async-backend",
        label: "비동기 I/O 백엔드",
        doc: "Configures the low-level API to use for async IO, eventing, etc.",
        kind: Kind::Enum(&["auto", "epoll", "kqueue", "io_uring"]),
        hint: "",
        platform: "",
    },
    // ---- 스크롤 · 마우스 -------------------------------------------------------------
    Opt {
        key: "scrollback-limit",
        label: "스크롤백 한도",
        doc: "Scrollback buffer size in bytes, including the active screen. Allocated lazily, per terminal surface.",
        kind: Kind::Int { min: 0, max: 10_000_000_000 },
        hint: "바이트",
        platform: "",},
    Opt {
        key: "scrollbar",
        label: "스크롤바 표시",
        doc: "`system` respects the OS scrollbar settings; `never` hides the visual bar while keeping wheel scrolling.",
        kind: Kind::Enum(&["system", "never"]),
        hint: "",
        platform: "",},
    Opt {
        key: "scroll-to-bottom",
        label: "바닥으로 스크롤",
        doc: "When to jump to the bottom. Default is keystroke with no-output.",
        kind: Kind::Flags(&["keystroke", "output"]),
        hint: "",
        platform: "",},
    Opt {
        key: "mouse-hide-while-typing",
        label: "입력 중 마우스 숨기기",
        doc: "Hide the mouse pointer as soon as typing starts; show it again on mouse activity.",
        kind: Kind::Bool,
        hint: "",
        platform: "",},
    Opt {
        key: "mouse-scroll-multiplier",
        label: "스크롤 배율",
        doc: "Scroll distance multiplier, clamped to 0.01–10000. Prefixed forms target one device class.",
        kind: Kind::Text,
        hint: "예: 3 또는 precision:1,discrete:3",
        platform: "",},
    Opt {
        key: "mouse-shift-capture",
        label: "Shift+클릭 캡처",
        doc: "Whether applications can see the shift key with a mouse click. `never` always keeps shift for selection.",
        kind: Kind::Enum(&["false", "true", "always", "never"]),
        hint: "",
        platform: "",},
    Opt {
        key: "mouse-reporting",
        label: "마우스 리포팅",
        doc: "Allow applications to capture mouse events. Off keeps the mouse for selection and Ghostty's own UI.",
        kind: Kind::Bool,
        hint: "",
        platform: "",},
    Opt {
        key: "click-repeat-interval",
        label: "클릭 반복 간격",
        doc: "The time in milliseconds between clicks to consider a click a repeat (double, triple, etc.) or an entirely new single click. A value of zero will use a platf...",
        kind: Kind::Int { min: 0, max: 5000 },
        hint: "ms",
        platform: "",
    },
    Opt {
        key: "right-click-action",
        label: "우클릭 동작",
        doc: "The action to take when the user right-clicks on the terminal surface.",
        kind: Kind::Enum(&["context-menu", "paste"]),
        hint: "",
        platform: "",
    },
    Opt {
        key: "focus-follows-mouse",
        label: "마우스로 포커스",
        doc: "Focus a split when the mouse moves over it.",
        kind: Kind::Bool,
        hint: "",
        platform: "",},
    // ---- 동작 -------------------------------------------------------------
    Opt {
        key: "title",
        label: "창 제목",
        doc: "Requested window title. Programs can override it at runtime.",
        kind: Kind::Text,
        hint: "",
        platform: "",},
    Opt {
        key: "title-report",
        label: "창 제목 보고 허용 (CSI 21 t)",
        doc: "Enables or disabled title reporting (CSI 21 t). This escape sequence allows the running program to query the terminal title. This is a common security issue ...",
        kind: Kind::Bool,
        hint: "",
        platform: "",
    },
    Opt {
        key: "confirm-close-surface",
        label: "닫기 확인",
        doc: "Ask for confirmation before closing a surface that is running a command other than a bare shell.",
        kind: Kind::Bool,
        hint: "",
        platform: "",},
    Opt {
        key: "quit-after-last-window-closed",
        label: "마지막 창 닫으면 종료",
        doc: "Exit the Ghostty process once the last window is closed.",
        kind: Kind::Bool,
        hint: "",
        platform: "",},
    Opt {
        key: "quit-after-last-window-closed-delay",
        label: "마지막 창 닫힌 후 종료 대기",
        doc: "Controls how long Ghostty will stay running after the last open surface has been closed. This only has an effect if `quit-after-last-window-closed` is also s...",
        kind: Kind::Text,
        hint: "예: 5s, 1m",
        platform: "",
    },
    Opt {
        key: "link-previews",
        label: "링크 미리보기",
        doc: "Show a preview for a matched URL. `osc8` limits previews to OSC 8 hyperlinks.",
        kind: Kind::Enum(&["true", "false", "osc8"]),
        hint: "",
        platform: "",},
    Opt {
        key: "link-url",
        label: "URL 자동 인식",
        doc: "Enable URL matching. URLs are matched on hover with control (Linux) or command (macOS) pressed and open using the default system application for the linked URL.",
        kind: Kind::Bool,
        hint: "",
        platform: "",
    },
    Opt {
        key: "auto-update",
        label: "자동 업데이트",
        doc: "Check, download, or disable updates. macOS only; Linux builds update through their package manager.",
        kind: Kind::Enum(&["off", "check", "download"]),
        hint: "",
        platform: MACOS,},
    Opt {
        key: "auto-update-channel",
        label: "업데이트 채널",
        doc: "Release channel for updates. Defaults to the channel of the running version.",
        kind: Kind::Enum(&["stable", "tip"]),
        hint: "",
        platform: MACOS,},
    Opt {
        key: "config-file",
        label: "추가 설정 파일",
        doc: "Other config files to read. They are loaded after this file, so their values win. Prefix with `?` to make a file optional.",
        kind: Kind::List,
        hint: "각 줄에 경로",
        platform: "",},
    Opt {
        key: "config-default-files",
        label: "기본 설정 파일 로드",
        doc: "When this is true, the default configuration file paths will be loaded. The default configuration file paths are currently only the XDG config path ($XDG_CON...",
        kind: Kind::Bool,
        hint: "",
        platform: "",
    },
    Opt {
        key: "keybind",
        label: "키 바인딩",
        doc: "Trigger=action pairs. Duplicate triggers overwrite earlier ones. `ghostty +list-actions` prints every action.",
        kind: Kind::List,
        hint: "각 줄에 trigger=action",
        platform: "",},
    Opt {
        key: "key-remap",
        label: "키 리맵",
        doc: "Remap modifier keys within Ghostty. This allows you to swap or reassign modifier keys at the application level without affecting system-wide settings.",
        kind: Kind::List,
        hint: "physical=logical",
        platform: "",
    },
    Opt {
        key: "bell-features",
        label: "벨 알림 기능",
        doc: "Bell features to enable if bell support is available in your runtime. Not all features are available on all runtimes. The format of this is a list of feature...",
        kind: Kind::Flags(&["system", "audio", "attention", "title", "border"]),
        hint: "",
        platform: "",
    },
    Opt {
        key: "bell-audio-path",
        label: "벨 오디오 파일",
        doc: "If `audio` is an enabled bell feature, this is a path to an audio file. If the path is not absolute, it is considered relative to the directory of the config...",
        kind: Kind::Text,
        hint: "오디오 파일 경로",
        platform: "",
    },
    Opt {
        key: "bell-audio-volume",
        label: "벨 볼륨",
        doc: "If `audio` is an enabled bell feature, this is the volume to play the audio file at (relative to the system volume). This is a floating point number ranging ...",
        kind: Kind::Float { min: 0.0, max: 1.0 },
        hint: "0.0 – 1.0",
        platform: "",
    },
    Opt {
        key: "app-notifications",
        label: "앱 내부 알림",
        doc: "Control the in-app notifications that Ghostty shows.",
        kind: Kind::Flags(&["clipboard-copy", "config-reload"]),
        hint: "",
        platform: "",
    },
    Opt {
        key: "desktop-notifications",
        label: "데스크톱 시스템 알림",
        doc: "If `true` (default), applications running in the terminal can show desktop notifications using certain escape sequences such as OSC 9 or OSC 777.",
        kind: Kind::Bool,
        hint: "",
        platform: "",
    },
    Opt {
        key: "macos-auto-secure-input",
        label: "자동 보안 입력 모드",
        doc: "If true, Ghostty on macOS will automatically enable the \"Secure Input\" feature when it detects that a password prompt is being displayed.",
        kind: Kind::Bool,
        hint: "",
        platform: MACOS,
    },
    Opt {
        key: "macos-secure-input-indication",
        label: "보안 입력 시각적 표시",
        doc: "If true, Ghostty will show a graphical indication when secure input is enabled. This indication is generally recommended to know when secure input is enabled.",
        kind: Kind::Bool,
        hint: "",
        platform: MACOS,
    },
    Opt {
        key: "macos-shortcuts",
        label: "macOS 단축어(Shortcuts) 허용",
        doc: "Whether macOS Shortcuts are allowed to control Ghostty.",
        kind: Kind::Enum(&["ask", "allow", "deny"]),
        hint: "",
        platform: MACOS,
    },
    Opt {
        key: "custom-shader",
        label: "커스텀 셰이더",
        doc: "Custom shaders to run after the default shaders. This is a file path to a GLSL-syntax shader for all platforms.",
        kind: Kind::Text,
        hint: "셰이더 파일 경로",
        platform: "",
    },
    Opt {
        key: "custom-shader-animation",
        label: "셰이더 애니메이션",
        doc: "If `true` (default), the focused terminal surface will run an animation loop when custom shaders are used. This uses slightly more CPU (generally less than 1...",
        kind: Kind::Bool,
        hint: "",
        platform: "",
    },
    Opt {
        key: "image-storage-limit",
        label: "이미지 저장 용량 한도",
        doc: "The total amount of bytes that can be used for image data (e.g. the Kitty image protocol) per terminal screen. The maximum value is 4,294,967,295 (4GiB). The...",
        kind: Kind::Int { min: 0, max: 10_000_000_000 },
        hint: "바이트",
        platform: "",
    },
    Opt {
        key: "progress-style",
        label: "진행 상태 표시줄 지원",
        doc: "If `true` (default), applications running in the terminal can show graphical progress bars using the ConEmu OSC 9;4 escape sequence. If `false`, progress bar...",
        kind: Kind::Bool,
        hint: "",
        platform: "",
    },
    Opt {
        key: "resize-overlay",
        label: "창 크기 오버레이 표시",
        doc: "This controls when resize overlays are shown. Resize overlays are a transient popup that shows the size of the terminal while the surfaces are being resized....",
        kind: Kind::Enum(&["always", "never", "after-first"]),
        hint: "",
        platform: "",
    },
    Opt {
        key: "resize-overlay-position",
        label: "크기 오버레이 위치",
        doc: "If resize overlays are enabled, this controls the position of the overlay. The possible options are:",
        kind: Kind::Enum(&["center", "top-left", "top-right", "bottom-left", "bottom-right"]),
        hint: "",
        platform: "",
    },
    Opt {
        key: "resize-overlay-duration",
        label: "크기 오버레이 표시 시간",
        doc: "If resize overlays are enabled, this controls how long the overlay is visible on the screen before it is hidden. The default is ¾ of a second or 750 ms.",
        kind: Kind::Text,
        hint: "예: 750ms",
        platform: "",
    },
    Opt {
        key: "undo-timeout",
        label: "실행 취소 유효 시간",
        doc: "The duration that undo operations remain available. After this time, the operation will be removed from the undo stack and cannot be undone.",
        kind: Kind::Text,
        hint: "예: 5s",
        platform: "",
    },
    Opt {
        key: "osc-color-report-format",
        label: "OSC 색상 보고 포맷",
        doc: "Sets the reporting format for OSC sequences that request color information. Ghostty currently supports OSC 10 (foreground), OSC 11 (background), and OSC 4 (2...",
        kind: Kind::Enum(&["16-bit", "8-bit"]),
        hint: "",
        platform: "",
    },
    Opt {
        key: "command-palette-entry",
        label: "커맨드 팔레트 항목",
        doc: "Custom entries into the command palette.",
        kind: Kind::List,
        hint: "title=action",
        platform: "",
    },
    Opt {
        key: "language",
        label: "GUI 언어",
        doc: "Set Ghostty's graphical user interface language to a language other than the system default language. For example:",
        kind: Kind::Text,
        hint: "예: ko, en, ja",
        platform: "",
    },
];

pub static CATEGORIES: &[Category] = &[
    Category {
        label: "글꼴",
        desc: "글꼴, 크기, 셀 크기, OpenType 기능",
        keys: &[
            "font-family",
            "font-family-bold",
            "font-family-italic",
            "font-family-bold-italic",
            "font-style",
            "font-style-bold",
            "font-style-italic",
            "font-style-bold-italic",
            "font-size",
            "font-feature",
            "font-thicken",
            "font-thicken-strength",
            "font-variation",
            "font-variation-bold",
            "font-variation-italic",
            "font-variation-bold-italic",
            "font-codepoint-map",
            "font-synthetic-style",
            "font-shaping-break",
            "freetype-load-flags",
            "adjust-cell-width",
            "adjust-cell-height",
            "adjust-font-baseline",
            "adjust-underline-position",
            "adjust-underline-thickness",
            "adjust-overline-position",
            "adjust-overline-thickness",
            "adjust-strikethrough-position",
            "adjust-strikethrough-thickness",
            "adjust-box-thickness",
            "adjust-icon-height",
            "grapheme-width-method",
        ],
    },
    Category {
        label: "테마 · 색상",
        desc: "배경, 글자, 대비, 팔레트, 배경 이미지",
        keys: &[
            "theme",
            "window-theme",
            "background",
            "foreground",
            "bold-color",
            "background-opacity",
            "background-opacity-cells",
            "background-blur",
            "background-image",
            "background-image-opacity",
            "background-image-position",
            "background-image-repeat",
            "background-image-fit",
            "minimum-contrast",
            "faint-opacity",
            "alpha-blending",
            "palette",
            "palette-generate",
            "palette-harmonious",
            "search-background",
            "search-foreground",
            "search-selected-background",
            "search-selected-foreground",
            "split-divider-color",
            "unfocused-split-fill",
            "unfocused-split-opacity",
            "window-padding-color",
            "window-titlebar-background",
            "window-titlebar-foreground",
        ],
    },
    Category {
        label: "커서",
        desc: "모양, 색, 깜빡임, 크기 조정",
        keys: &[
            "cursor-style",
            "cursor-style-blink",
            "cursor-color",
            "cursor-text",
            "cursor-opacity",
            "cursor-click-to-move",
            "adjust-cursor-height",
            "adjust-cursor-thickness",
        ],
    },
    Category {
        label: "선택 · 클립보드",
        desc: "선택 영역, 복사와 붙여넣기, 클립보드 보안",
        keys: &[
            "selection-background",
            "selection-foreground",
            "selection-clear-on-typing",
            "selection-clear-on-copy",
            "copy-on-select",
            "selection-word-chars",
            "clipboard-paste-protection",
            "clipboard-paste-bracketed-safe",
            "clipboard-trim-trailing-spaces",
            "clipboard-read",
            "clipboard-write",
            "clipboard-codepoint-map",
        ],
    },
    Category {
        label: "창 · 탭",
        desc: "크기, 여백, 장식, 타이틀바, 탭, 분할창, 퀵 터미널",
        keys: &[
            "window-width",
            "window-height",
            "window-padding-x",
            "window-padding-y",
            "window-padding-balance",
            "window-position-x",
            "window-position-y",
            "window-decoration",
            "window-save-state",
            "window-step-resize",
            "window-new-tab-position",
            "window-show-tab-bar",
            "window-vsync",
            "window-colorspace",
            "window-inherit-working-directory",
            "window-inherit-font-size",
            "window-subtitle",
            "window-title-font-family",
            "initial-window",
            "fullscreen",
            "maximize",
            "macos-titlebar-style",
            "macos-titlebar-proxy-icon",
            "macos-window-buttons",
            "macos-window-shadow",
            "macos-non-native-fullscreen",
            "macos-option-as-alt",
            "macos-hidden",
            "macos-icon",
            "macos-icon-frame",
            "macos-icon-ghost-color",
            "macos-icon-screen-color",
            "macos-custom-icon",
            "macos-dock-drop-behavior",
            "macos-applescript",
            "gtk-titlebar",
            "gtk-titlebar-style",
            "gtk-titlebar-hide-when-maximized",
            "gtk-toolbar-style",
            "gtk-tabs-location",
            "gtk-wide-tabs",
            "gtk-single-instance",
            "gtk-custom-css",
            "gtk-opengl-debug",
            "gtk-quick-terminal-layer",
            "gtk-quick-terminal-namespace",
            "quick-terminal-position",
            "quick-terminal-screen",
            "quick-terminal-animation-duration",
            "quick-terminal-autohide",
            "quick-terminal-keyboard-interactivity",
            "quick-terminal-space-behavior",
            "tab-inherit-working-directory",
            "split-inherit-working-directory",
            "split-preserve-zoom",
        ],
    },
    Category {
        label: "셸 · 실행",
        desc: "셸, 환경 변수, 알림, 리눅스 격리",
        keys: &[
            "command",
            "initial-command",
            "working-directory",
            "input",
            "shell-integration",
            "shell-integration-features",
            "env",
            "term",
            "enquiry-response",
            "vt-kam-allowed",
            "class",
            "x11-instance-name",
            "linux-cgroup",
            "linux-cgroup-hard-fail",
            "linux-cgroup-memory-limit",
            "linux-cgroup-processes-limit",
            "abnormal-command-exit-runtime",
            "notify-on-command-finish",
            "notify-on-command-finish-action",
            "notify-on-command-finish-after",
            "wait-after-command",
            "async-backend",
        ],
    },
    Category {
        label: "스크롤 · 마우스",
        desc: "스크롤백, 휠, 포커스, 마우스 동작",
        keys: &[
            "scrollback-limit",
            "scrollbar",
            "scroll-to-bottom",
            "mouse-hide-while-typing",
            "mouse-scroll-multiplier",
            "mouse-shift-capture",
            "mouse-reporting",
            "click-repeat-interval",
            "right-click-action",
            "focus-follows-mouse",
        ],
    },
    Category {
        label: "동작",
        desc: "단축키, 업데이트, 벨, 셰이더, 기타 동작",
        keys: &[
            "title",
            "title-report",
            "confirm-close-surface",
            "quit-after-last-window-closed",
            "quit-after-last-window-closed-delay",
            "link-previews",
            "link-url",
            "auto-update",
            "auto-update-channel",
            "config-file",
            "config-default-files",
            "keybind",
            "key-remap",
            "bell-features",
            "bell-audio-path",
            "bell-audio-volume",
            "app-notifications",
            "desktop-notifications",
            "macos-auto-secure-input",
            "macos-secure-input-indication",
            "macos-shortcuts",
            "custom-shader",
            "custom-shader-animation",
            "image-storage-limit",
            "progress-style",
            "resize-overlay",
            "resize-overlay-position",
            "resize-overlay-duration",
            "undo-timeout",
            "osc-color-report-format",
            "command-palette-entry",
            "language",
        ],
    },
];

pub fn lookup(key: &str) -> Option<&'static Opt> {
    OPTS.iter().find(|o| o.key == key)
}
