//! Metadata for the Ghostty options this GUI edits.
//!
//! Only a curated subset of Ghostty's 240+ keys is modelled here — the ones
//! people actually reach for. Everything else stays editable through the raw
//! editor. Option names and enum value sets are taken verbatim from
//! https://ghostty.org/docs/config/reference.

/// How a value is shaped, which decides both the widget and the validation.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum Kind {
    /// `true` / `false`, plus unset (= Ghostty default).
    Bool,
    Int { min: i64, max: i64 },
    Float { min: f64, max: f64 },
    /// Hex, an X11 color name, or one of `special`.
    Color { special: &'static [&'static str] },
    /// One of a fixed set, plus unset.
    Enum(&'static [&'static str]),
    /// Free-form single string.
    Text,
    /// Repeatable key (font-family, env, keybind, palette, ...).
    List,
    /// Comma list where an item may be prefixed with `no-`.
    Flags(&'static [&'static str]),
}

pub struct Opt {
    pub key: &'static str,
    pub label: &'static str,
    pub doc: &'static str,
    pub kind: Kind,
    /// Short usage hint shown under the widget.
    pub hint: &'static str,
    /// Non-empty when the option only applies to one platform.
    pub platform: &'static str,
}

impl Opt {
    /// `true` when the key may appear more than once in the file.
    pub fn repeatable(&self) -> bool {
        matches!(self.kind, Kind::List)
    }
}

pub struct Category {
    pub label: &'static str,
    pub desc: &'static str,
    pub keys: &'static [&'static str],
}

const MACOS: &str = "macOS";
const GTK: &str = "GTK";

/// All options, keyed by `key`.
pub static OPTS: &[Opt] = &[
    // ---- Font -------------------------------------------------------------
    Opt {
        key: "font-family",
        label: "글꼴",
        doc: "Primary font, then fallbacks in preference order. Repeat the key for each fallback. `ghostty +list-fonts` prints the valid names.",
        kind: Kind::List,
        hint: "각 줄에 글꼴 하나",
        platform: "",
    },
    Opt {
        key: "font-size",
        label: "글꼴 크기",
        doc: "Font size in points. Non-integers are allowed (13.5) and round to the nearest pixel on high-DPI displays.",
        kind: Kind::Float { min: 1.0, max: 200.0 },
        hint: "pt",
        platform: "",
    },
    Opt {
        key: "font-style",
        label: "글꼴 스타일",
        doc: "Named font style as advertised by the font itself, e.g. \"Iosevka Heavy\". Set to `false` to disable this style entirely.",
        kind: Kind::Text,
        hint: "예: Heavy, false",
        platform: "",
    },
    Opt {
        key: "font-feature",
        label: "OpenType 기능",
        doc: "Font features to apply, e.g. `-calt` to disable programming ligatures. Repeat the key or comma-separate values.",
        kind: Kind::List,
        hint: "예: -calt, -liga, -dlig",
        platform: "",
    },
    Opt {
        key: "font-thicken",
        label: "글꼴 두껍게",
        doc: "Draw fonts with a thicker stroke.",
        kind: Kind::Bool,
        hint: "",
        platform: MACOS,
    },
    Opt {
        key: "font-thicken-strength",
        label: "두께 강도",
        doc: "Strength of thickening when font-thicken is enabled. 0 is the lightest, not \"off\".",
        kind: Kind::Int { min: 0, max: 255 },
        hint: "0–255",
        platform: MACOS,
    },
    Opt {
        key: "adjust-cell-width",
        label: "셀 너비 조정",
        doc: "Amount to change the cell width determined by the font. An integer is an absolute delta, a percentage is relative.",
        kind: Kind::Text,
        hint: "예: 1, -1, 20%, -15%",
        platform: "",
    },
    Opt {
        key: "adjust-cell-height",
        label: "셀 높이 조정",
        doc: "Amount to change the cell height. Also centers the font in the cell and scales Powerline glyphs with it.",
        kind: Kind::Text,
        hint: "예: 1, -1, 20%, -15%",
        platform: "",
    },
    Opt {
        key: "grapheme-width-method",
        label: "글리프 폭 계산",
        doc: "How to measure grapheme cluster width. `unicode` is correct but can desync with programs using a legacy wcswidth.",
        kind: Kind::Enum(&["unicode", "legacy"]),
        hint: "",
        platform: "",
    },

    // ---- Theme & colors ---------------------------------------------------
    Opt {
        key: "theme",
        label: "테마",
        doc: "Built-in theme name, custom theme name, or absolute path. Supports light/dark pairs as `light:Dawn,dark:Rose Pine`.",
        kind: Kind::Text,
        hint: "ghostty +list-themes",
        platform: "",
    },
    Opt {
        key: "window-theme",
        label: "창 테마",
        doc: "`auto` derives the window theme from the terminal background color; `ghostty` uses the configured colors directly (Linux only).",
        kind: Kind::Enum(&["auto", "system", "light", "dark", "ghostty"]),
        hint: "",
        platform: "",
    },
    Opt {
        key: "background",
        label: "배경색",
        doc: "Background color for the window.",
        kind: Kind::Color { special: &[] },
        hint: "#RRGGBB 또는 X11 색상명",
        platform: "",
    },
    Opt {
        key: "foreground",
        label: "글자색",
        doc: "Foreground color for the window.",
        kind: Kind::Color { special: &[] },
        hint: "#RRGGBB 또는 X11 색상명",
        platform: "",
    },
    Opt {
        key: "background-opacity",
        label: "배경 불투명도",
        doc: "1 is fully opaque, 0 fully transparent. On macOS changing this requires a full restart.",
        kind: Kind::Float { min: 0.0, max: 1.0 },
        hint: "0.0 – 1.0",
        platform: "",
    },
    Opt {
        key: "background-blur",
        label: "배경 블러",
        doc: "Blur behind a translucent background. Accepts true, false, an intensity (default 20), or on macOS 26+ `macos-glass-regular` / `macos-glass-clear`.",
        kind: Kind::Text,
        hint: "true / false / 정수 / macos-glass-*",
        platform: "",
    },
    Opt {
        key: "minimum-contrast",
        label: "최소 대비",
        doc: "Minimum WCAG contrast ratio between foreground and background. 1 allows no contrast; 3+ avoids hard-to-read text.",
        kind: Kind::Float { min: 1.0, max: 21.0 },
        hint: "1 – 21",
        platform: "",
    },
    Opt {
        key: "bold-color",
        label: "굵은 글자색",
        doc: "Color used for bold text. Set to `bright` to reproduce the old bold-is-bright behavior.",
        kind: Kind::Color { special: &["bright"] },
        hint: "#RRGGBB 또는 bright",
        platform: "",
    },
    Opt {
        key: "palette",
        label: "색상 팔레트",
        doc: "The 256-color table, as `N=#COLOR`. You usually only need indices 0–15; 16–255 can be generated with palette-generate.",
        kind: Kind::List,
        hint: "각 줄에 0=#RRGGBB",
        platform: "",
    },

    // ---- Cursor -----------------------------------------------------------
    Opt {
        key: "cursor-style",
        label: "커서 모양",
        doc: "Default cursor style. A running program can still override it with DECSCUSR, and shell integration forces a bar at prompts unless disabled.",
        kind: Kind::Enum(&["block", "bar", "underline", "block_hollow"]),
        hint: "",
        platform: "",
    },
    Opt {
        key: "cursor-style-blink",
        label: "커서 깜빡임",
        doc: "Default blinking state. Leaving this unset lets Ghostty honour DEC mode 12 as well as DECSCUSR.",
        kind: Kind::Enum(&["true", "false"]),
        hint: "기본값 = DEC mode 12 준수",
        platform: "",
    },
    Opt {
        key: "cursor-color",
        label: "커서 색",
        doc: "Color of the cursor, or a special value to track the cell underneath it.",
        kind: Kind::Color { special: &["cell-foreground", "cell-background"] },
        hint: "#RRGGBB 또는 cell-foreground",
        platform: "",
    },
    Opt {
        key: "cursor-text",
        label: "커서 위 글자색",
        doc: "Color of the text under the cursor.",
        kind: Kind::Color { special: &["cell-foreground", "cell-background"] },
        hint: "#RRGGBB",
        platform: "",
    },
    Opt {
        key: "cursor-opacity",
        label: "커서 불투명도",
        doc: "1 is fully opaque, 0 fully transparent. Values far below 1 make the cursor hard to find.",
        kind: Kind::Float { min: 0.0, max: 1.0 },
        hint: "0.0 – 1.0",
        platform: "",
    },
    Opt {
        key: "cursor-click-to-move",
        label: "클릭으로 커서 이동",
        doc: "Move the cursor at a shell prompt by clicking in the prompt text. Requires prompt marking (OSC 133) via shell integration.",
        kind: Kind::Bool,
        hint: "",
        platform: "",
    },

    // ---- Selection & clipboard -------------------------------------------
    Opt {
        key: "selection-background",
        label: "선택 영역 배경",
        doc: "Selection background. Unset, selection is drawn as the inverted window colors.",
        kind: Kind::Color { special: &["cell-foreground", "cell-background"] },
        hint: "#RRGGBB",
        platform: "",
    },
    Opt {
        key: "selection-foreground",
        label: "선택 영역 글자색",
        doc: "Selection foreground.",
        kind: Kind::Color { special: &["cell-foreground", "cell-background"] },
        hint: "#RRGGBB",
        platform: "",
    },
    Opt {
        key: "selection-clear-on-typing",
        label: "입력 시 선택 해제",
        doc: "Clear the selection when a non-modifier key sends data to the application. Clearing still works via a click or Escape when off.",
        kind: Kind::Bool,
        hint: "",
        platform: "",
    },
    Opt {
        key: "copy-on-select",
        label: "선택 시 복사",
        doc: "`true` prefers the selection clipboard; `clipboard` writes both the selection and system clipboard. Middle-click paste always works.",
        kind: Kind::Enum(&["true", "false", "clipboard"]),
        hint: "",
        platform: "",
    },
    Opt {
        key: "selection-word-chars",
        label: "단어 경계 문자",
        doc: "Characters that bound a double-click word selection, like WORDCHARS in zsh. Each character is a boundary; sequences are not supported.",
        kind: Kind::Text,
        hint: "기본: \\t'\"│`|:;,()[]{}<>$",
        platform: "",
    },
    Opt {
        key: "clipboard-paste-protection",
        label: "붙여넣기 보호",
        doc: "Confirm before pasting control characters that could execute in a shell.",
        kind: Kind::Bool,
        hint: "",
        platform: "",
    },
    Opt {
        key: "clipboard-trim-trailing-spaces",
        label: "복사 시 공백 정리",
        doc: "Trim trailing spaces from each line when copying.",
        kind: Kind::Bool,
        hint: "",
        platform: "",
    },

    // ---- Window -----------------------------------------------------------
    Opt {
        key: "window-width",
        label: "창 너비",
        doc: "Initial window width in terminal grid cells. Ignored unless window-height is also set.",
        kind: Kind::Int { min: 1, max: 10000 },
        hint: "글리프 셀 수",
        platform: "",
    },
    Opt {
        key: "window-height",
        label: "창 높이",
        doc: "Initial window height in terminal grid cells. Ignored unless window-width is also set.",
        kind: Kind::Int { min: 1, max: 10000 },
        hint: "글리프 셀 수",
        platform: "",
    },
    Opt {
        key: "window-padding-x",
        label: "가로 여백",
        doc: "Horizontal padding in points. Give two comma-separated values to set left and right independently.",
        kind: Kind::Text,
        hint: "예: 4 또는 2,4",
        platform: "",
    },
    Opt {
        key: "window-padding-y",
        label: "세로 여백",
        doc: "Vertical padding in points. Give two comma-separated values to set top and bottom independently.",
        kind: Kind::Text,
        hint: "예: 4 또는 2,4",
        platform: "",
    },
    Opt {
        key: "window-decoration",
        label: "창 장식",
        doc: "Preference for titlebar and borders. The OS may override it. `none` also disables macOS tabs.",
        kind: Kind::Enum(&["auto", "none", "client", "server"]),
        hint: "",
        platform: "",
    },
    Opt {
        key: "window-save-state",
        label: "창 상태 저장",
        doc: "Save and restore position, size, tabs and splits. macOS only.",
        kind: Kind::Enum(&["default", "never", "always"]),
        hint: "",
        platform: MACOS,
    },
    Opt {
        key: "window-step-resize",
        label: "셀 단위 크기 조절",
        doc: "Resize the window in whole cell increments instead of pixel increments.",
        kind: Kind::Bool,
        hint: "",
        platform: MACOS,
    },
    Opt {
        key: "window-new-tab-position",
        label: "새 탭 위치",
        doc: "Where a newly created tab is inserted.",
        kind: Kind::Enum(&["current", "end"]),
        hint: "",
        platform: "",
    },
    Opt {
        key: "window-show-tab-bar",
        label: "탭 표시줄",
        doc: "`auto` shows the bar only with two or more tabs. Linux only.",
        kind: Kind::Enum(&["auto", "always", "never"]),
        hint: "",
        platform: GTK,
    },
    Opt {
        key: "macos-titlebar-style",
        label: "macOS 타이틀바",
        doc: "`transparent` lets the terminal background show through; `tabs` folds the tab bar into the titlebar; `hidden` keeps the frame and rounded corners.",
        kind: Kind::Enum(&["native", "transparent", "tabs", "hidden"]),
        hint: "",
        platform: MACOS,
    },
    Opt {
        key: "macos-window-buttons",
        label: "macOS 신호등 버튼",
        doc: "Show or hide the close/minimize/zoom buttons. No effect when window-decoration is none or the titlebar is hidden.",
        kind: Kind::Enum(&["visible", "hidden"]),
        hint: "",
        platform: MACOS,
    },
    Opt {
        key: "macos-non-native-fullscreen",
        label: "전체화면 방식",
        doc: "Non-native fullscreen is faster but breaks macOS tabs. `padded-notch` keeps the notch area clear.",
        kind: Kind::Enum(&["false", "true", "visible-menu", "padded-notch"]),
        hint: "",
        platform: MACOS,
    },
    Opt {
        key: "macos-option-as-alt",
        label: "Option을 Alt로",
        doc: "Treat the Option key as Alt so terminal sequences work, at the cost of Unicode input sequences produced with Option.",
        kind: Kind::Enum(&["true", "false", "left", "right"]),
        hint: "기본값은 키보드 레이아웃에 따라 다름",
        platform: MACOS,
    },

    // ---- Shell ------------------------------------------------------------
    Opt {
        key: "command",
        label: "실행 명령",
        doc: "Command to run, usually a shell. Searched on PATH if not absolute. Prefix `direct:` to skip shell expansion or `shell:` to force it.",
        kind: Kind::Text,
        hint: "예: /bin/zsh, direct:nvim foo",
        platform: "",
    },
    Opt {
        key: "working-directory",
        label: "작업 디렉터리",
        doc: "Working directory for new terminals. A path starting with `~` is expanded.",
        kind: Kind::Text,
        hint: "예: ~",
        platform: "",
    },
    Opt {
        key: "shell-integration",
        label: "셸 통합",
        doc: "Auto-inject shell integration, or name the shell to inject into. Integration gives prompt marking, working directory reporting and inherited splits.",
        kind: Kind::Enum(&["detect", "none", "bash", "elvish", "fish", "nushell", "zsh"]),
        hint: "",
        platform: "",
    },
    Opt {
        key: "shell-integration-features",
        label: "셸 통합 기능",
        doc: "Features to enable. Prefix with `no-` to disable, or use true/false for everything.",
        kind: Kind::Flags(&["cursor", "sudo", "title", "ssh-env", "ssh-terminfo", "path"]),
        hint: "",
        platform: "",
    },
    Opt {
        key: "env",
        label: "환경 변수",
        doc: "Extra environment variables passed to commands launched in a terminal surface. An empty value removes that key.",
        kind: Kind::List,
        hint: "각 줄에 KEY=VALUE",
        platform: "",
    },
    Opt {
        key: "notify-on-command-finish",
        label: "명령 종료 알림",
        doc: "When to notify that a command finished. Requires shell integration or OSC 133 from the shell.",
        kind: Kind::Enum(&["never", "unfocused", "always"]),
        hint: "",
        platform: "",
    },
    Opt {
        key: "wait-after-command",
        label: "종료 후 대기",
        doc: "Keep the terminal open after the command exits, until a key is pressed. Useful for scripts and debugging.",
        kind: Kind::Bool,
        hint: "",
        platform: "",
    },

    // ---- Scroll & mouse ---------------------------------------------------
    Opt {
        key: "scrollback-limit",
        label: "스크롤백 한도",
        doc: "Scrollback buffer size in bytes, including the active screen. Allocated lazily, per terminal surface.",
        kind: Kind::Int { min: 0, max: 10_000_000_000 },
        hint: "바이트",
        platform: "",
    },
    Opt {
        key: "scrollbar",
        label: "스크롤바 표시",
        doc: "`system` respects the OS scrollbar settings; `never` hides the visual bar while keeping wheel scrolling.",
        kind: Kind::Enum(&["system", "never"]),
        hint: "",
        platform: "",
    },
    Opt {
        key: "scroll-to-bottom",
        label: "바닥으로 스크롤",
        doc: "When to jump to the bottom. Default is keystroke with no-output.",
        kind: Kind::Flags(&["keystroke", "output"]),
        hint: "",
        platform: "",
    },
    Opt {
        key: "mouse-hide-while-typing",
        label: "입력 중 마우스 숨기기",
        doc: "Hide the mouse pointer as soon as typing starts; show it again on mouse activity.",
        kind: Kind::Bool,
        hint: "",
        platform: "",
    },
    Opt {
        key: "mouse-scroll-multiplier",
        label: "스크롤 배율",
        doc: "Scroll distance multiplier, clamped to 0.01–10000. Prefixed forms target one device class.",
        kind: Kind::Text,
        hint: "예: 3 또는 precision:1,discrete:3",
        platform: "",
    },
    Opt {
        key: "mouse-shift-capture",
        label: "Shift+클릭 캡처",
        doc: "Whether applications can see the shift key with a mouse click. `never` always keeps shift for selection.",
        kind: Kind::Enum(&["false", "true", "always", "never"]),
        hint: "",
        platform: "",
    },
    Opt {
        key: "mouse-reporting",
        label: "마우스 리포팅",
        doc: "Allow applications to capture mouse events. Off keeps the mouse for selection and Ghostty's own UI.",
        kind: Kind::Bool,
        hint: "",
        platform: "",
    },
    Opt {
        key: "focus-follows-mouse",
        label: "마우스로 포커스",
        doc: "Focus a split when the mouse moves over it.",
        kind: Kind::Bool,
        hint: "",
        platform: "",
    },

    // ---- Behavior ---------------------------------------------------------
    Opt {
        key: "title",
        label: "창 제목",
        doc: "Requested window title. Programs can override it at runtime.",
        kind: Kind::Text,
        hint: "",
        platform: "",
    },
    Opt {
        key: "confirm-close-surface",
        label: "닫기 확인",
        doc: "Ask for confirmation before closing a surface that is running a command other than a bare shell.",
        kind: Kind::Bool,
        hint: "",
        platform: "",
    },
    Opt {
        key: "quit-after-last-window-closed",
        label: "마지막 창 닫으면 종료",
        doc: "Exit the Ghostty process once the last window is closed.",
        kind: Kind::Bool,
        hint: "",
        platform: "",
    },
    Opt {
        key: "link-previews",
        label: "링크 미리보기",
        doc: "Show a preview for a matched URL. `osc8` limits previews to OSC 8 hyperlinks.",
        kind: Kind::Enum(&["true", "false", "osc8"]),
        hint: "",
        platform: "",
    },
    Opt {
        key: "auto-update",
        label: "자동 업데이트",
        doc: "Check, download, or disable updates. macOS only; Linux builds update through their package manager.",
        kind: Kind::Enum(&["off", "check", "download"]),
        hint: "",
        platform: MACOS,
    },
    Opt {
        key: "auto-update-channel",
        label: "업데이트 채널",
        doc: "Release channel for updates. Defaults to the channel of the running version.",
        kind: Kind::Enum(&["stable", "tip"]),
        hint: "",
        platform: MACOS,
    },
    Opt {
        key: "config-file",
        label: "추가 설정 파일",
        doc: "Other config files to read. They are loaded after this file, so their values win. Prefix with `?` to make a file optional.",
        kind: Kind::List,
        hint: "각 줄에 경로",
        platform: "",
    },
    Opt {
        key: "keybind",
        label: "키 바인딩",
        doc: "Trigger=action pairs. Duplicate triggers overwrite earlier ones. `ghostty +list-actions` prints every action.",
        kind: Kind::List,
        hint: "각 줄에 trigger=action",
        platform: "",
    },
];

pub static CATEGORIES: &[Category] = &[
    Category {
        label: "글꼴",
        desc: "글꼴, 크기, 셀 크기",
        keys: &[
            "font-family",
            "font-size",
            "font-style",
            "font-feature",
            "font-thicken",
            "font-thicken-strength",
            "adjust-cell-width",
            "adjust-cell-height",
            "grapheme-width-method",
        ],
    },
    Category {
        label: "테마 · 색상",
        desc: "배경, 글자, 대비, 팔레트",
        keys: &[
            "theme",
            "window-theme",
            "background",
            "foreground",
            "background-opacity",
            "background-blur",
            "minimum-contrast",
            "bold-color",
            "palette",
        ],
    },
    Category {
        label: "커서",
        desc: "모양, 색, 깜빡임",
        keys: &[
            "cursor-style",
            "cursor-style-blink",
            "cursor-color",
            "cursor-text",
            "cursor-opacity",
            "cursor-click-to-move",
        ],
    },
    Category {
        label: "선택 · 클립보드",
        desc: "선택 영역, 복사와 붙여넣기",
        keys: &[
            "selection-background",
            "selection-foreground",
            "selection-clear-on-typing",
            "copy-on-select",
            "selection-word-chars",
            "clipboard-paste-protection",
            "clipboard-trim-trailing-spaces",
        ],
    },
    Category {
        label: "창 · 탭",
        desc: "크기, 여백, 장식, 타이틀바",
        keys: &[
            "window-width",
            "window-height",
            "window-padding-x",
            "window-padding-y",
            "window-decoration",
            "window-save-state",
            "window-step-resize",
            "window-new-tab-position",
            "window-show-tab-bar",
            "macos-titlebar-style",
            "macos-window-buttons",
            "macos-non-native-fullscreen",
            "macos-option-as-alt",
        ],
    },
    Category {
        label: "셸 · 실행",
        desc: "셸, 환경 변수, 알림",
        keys: &[
            "command",
            "working-directory",
            "shell-integration",
            "shell-integration-features",
            "env",
            "notify-on-command-finish",
            "wait-after-command",
        ],
    },
    Category {
        label: "스크롤 · 마우스",
        desc: "스크롤백, 휠, 포커스",
        keys: &[
            "scrollback-limit",
            "scrollbar",
            "scroll-to-bottom",
            "mouse-hide-while-typing",
            "mouse-scroll-multiplier",
            "mouse-shift-capture",
            "mouse-reporting",
            "focus-follows-mouse",
        ],
    },
    Category {
        label: "동작",
        desc: "닫기, 링크, 업데이트, 키 바인딩",
        keys: &[
            "title",
            "confirm-close-surface",
            "quit-after-last-window-closed",
            "link-previews",
            "auto-update",
            "auto-update-channel",
            "config-file",
            "keybind",
        ],
    },
];

pub fn lookup(key: &str) -> Option<&'static Opt> {
    OPTS.iter().find(|o| o.key == key)
}
